name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup MSVC environment
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Build solution
        run: |
          msbuild /p:Configuration=Release /p:Platform="x64" Chrolispp.sln

      - name: Notify
        run: echo "Build and test completed successfully!"
